"""add-mask-image-path

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-26 00:00:00.000000

- Adds mask_image_path VARCHAR column to photos table.
  The mask generated by SAM during each edit-photo request is now
  persisted to Firebase Storage; the DB keeps only the GCS path.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b2c3d4e5f6a7'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('photos', sa.Column('mask_image_path', sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column('photos', 'mask_image_path')
